### ISSUE TITLE
Cannot load Driver class error in zeebe-simple-monitor:2.1.0

### ISSUE THREAD

**Issue by SiddarthSingh** [camunda-community-hub/zeebe-simple-monitor#303] opened 2021-10-04 13:50 UTC
Error : Caused by: java.lang.IllegalStateException: Cannot load driver class: org.postgresql.Driver
        at org.springframework.util.Assert.state(Assert.java:97) ~[spring-core-5.3.9.jar:5.3.9]

DockerFile:
FROM ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.1.0

COPY postgresql-42.2.23.jar /app/libs

Note:
Was working fine with 2.0.0 version of zeebe-simple-monitor

**Comment by saig0** [comment] 2021-10-04 17:39
This is a duplicate of #298. The issue should be fixed with #254.

**Closed by saig0** 2021-10-04 17:39 UTC
Labels: triage
