### ISSUE TITLE
When hazelcast is disconnected, how to give up retry after several retries

### ISSUE THREAD

**Issue by bugbugmaker** [camunda-community-hub/zeebe-simple-monitor#329] opened 2021-11-29 07:06 UTC
When hazelcast is disconnected, how to give up retry after several retries,The com.hazelcast.client.config.connectionretryconfig configuration is set but has no effect. The version of hazelcast is 4.2

**Comment by bugbugmaker** [comment] 2021-11-30 09:11
`final ClientConfig clientConfig = new ClientConfig();
    clientConfig.getNetworkConfig().addAddress(hazelcastConnection);

    final var connectionRetryConfig =
        clientConfig.getConnectionStrategyConfig().getConnectionRetryConfig();
    connectionRetryConfig.setClusterConnectTimeoutMillis(
        Duration.parse(hazelcastConnectionTimeout).toMillis());

    LOG.info("Connecting to Hazelcast '{}'", hazelcastConnection);

    final HazelcastInstance hazelcast = HazelcastClient.newHazelcastClient(clientConfig);

    LOG.info("Importing records from Hazelcast...");
    closeable = importService.importFrom(hazelcast);`
`zeebe:


  client:
    broker.contactPoint: localhost:26500
    security.plaintext: true

    worker:
      hazelcast:
        connection: localhost:5701
        connectionTimeout: PT30S`
The com.hazelcast.client.config.connectionretryconfig configuration is set but has no effect

**Comment by bugbugmaker** [comment] 2021-11-30 09:15
`
zeebe:
  client:
    broker.contactPoint: localhost:26500
    security.plaintext: true
    worker:
      hazelcast:
        connection: localhost:5701
        connectionTimeout: PT30S
`


` final ClientConfig clientConfig = new ClientConfig();
    clientConfig.getNetworkConfig().addAddress(hazelcastConnection);
    final var connectionRetryConfig = clientConfig.getConnectionStrategyConfig().getConnectionRetryConfig();
    connectionRetryConfig.setClusterConnectTimeoutMillis(
    Duration.parse(hazelcastConnectionTimeout).toMillis());
    LOG.info("Connecting to Hazelcast '{}'", hazelcastConnection);
    final HazelcastInstance hazelcast = HazelcastClient.newHazelcastClient(clientConfig);
    LOG.info("Importing records from Hazelcast...");
    closeable = importService.importFrom(hazelcast);`

**Comment by bugbugmaker** [comment] 2021-11-30 09:23
![image001](https://user-images.githubusercontent.com/17674768/144019919-b685db88-d815-4098-ac9f-68e506237778.png)
Crazy output of error logs like this will not stop if the program does not shut down forcibly

**Comment by saig0** [comment] 2021-12-01 08:48
@bugbugmaker which version of the simple monitor do you use?

**Comment by bugbugmaker** [comment] 2021-12-01 08:50
<version>2.0.0-SNAPSHOT</version>

**Comment by bugbugmaker** [comment] 2021-12-03 10:20
> @bugbugmaker which version of the simple monitor do you use?
2.0.0-SNAPSHOT，What causes it?

**Comment by saig0** [comment] 2021-12-07 05:57
The issue is a duplicate of #274. It is already fixed with version `2.1.0` :rocket:

**Closed by saig0** 2021-12-07 05:57 UTC
Labels: question
