### ISSUE TITLE
Cannot see created instances

### ISSUE THREAD

**Issue by nachoroncero** [camunda-community-hub/zeebe-simple-monitor#262] opened 2021-06-15 14:13 UTC
Hello,

I am using Zeebe version 1.0.0. I know there are some methods , related to deployment or create a workflow instance, which are different with respect to the original Zeebe version.

I am running my app with no exceptions or any issue, but when I go to localhost:8082, I do not see the instance I just created...

Why?

**Comment by saig0** [comment] 2021-06-18 03:33
Hi @nachoroncero,

please make sure that for Zeebe 1.0.0, you're running the following components:
* [Hazelcast exporter 1.0.0](https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/releases/tag/1.0.0)
* [Zeebe Simple Monitor 2.0.0](https://github.com/camunda-community-hub/zeebe-simple-monitor/releases/tag/2.0.0)

Do you still face the issue?

**Comment by nachoroncero** [comment] 2021-06-18 06:35
Hello,

How can I get the Zeebe Simple Monitor 2.0.0?

I want to use docker-compose, but the link provided in the manual downloads
Zeebe 1.0.0 and Zeebe Simple Monitor 1.0.0…

Is there any other link where I can get the second version for
docker-compose?

Thank you for answer

**Comment by saig0** [comment] 2021-06-18 07:12
The docker image was moved to GitHub packages. The new image is published under: 

``` 
ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.0.0
```
I updated the docs: https://github.com/camunda-community-hub/zeebe-simple-monitor#docker

Just a moment ago, I merged a PR to update the image in the `zeebe-docker-compose` repo: https://github.com/camunda-community-hub/zeebe-docker-compose/pull/44

**Comment by nachoroncero** [comment] 2021-06-18 07:19
Great, thank you.

Sorry for my questions but I am pretty new here.

So now,if I want to use Zeebe 1.0.0 and Simple Monitor 2.0.0,

Using the zeebe-docker-compose, I only run the directory that says only
broker, and then, I run with this command: docker pull
ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.0.0 for Simple Monitor
2.0.0?


Thank you

**Comment by saig0** [comment] 2021-06-18 09:25
No. You need to pull the latest updates from the `zeebe-docker-compose` repo. Afterward, you can start the broker and the monitor as usual. It should start the monitor in version 2.0.0.

**Comment by nitram509** [comment] 2021-08-03 14:07
Just guessing, but @nachoroncero do you have a multi-node-cluster of zeebe running?
If so, your reported issue might be related to #278.

**Comment by saig0** [comment] 2022-08-24 10:57
I'm closing this issue because of inactivity. Feel free to reopen if the issue is still relevant.

**Closed by saig0** 2022-08-24 10:57 UTC
Labels: triage
