### ISSUE TITLE
Features required on Instances table 

### ISSUE THREAD

**Issue by denisderossi** [camunda-community-hub/zeebe-simple-monitor#84] opened 2019-09-24 08:46 UTC
Hi,

we're starting to use Simple Monitor and we realized that pagination in the instances tab/section could be improved because that number of pages is not dynamic (only 1 is displayed) and there's no option to go to the first page or last page of the list.
Moreover, another useful thing would be a filters section so we could be able to filter, for instance, active vs terminated isntances.
And last nice to have feature would be the ordering on the columns for that table.

Thanks,
Diego

**Comment by saig0** [comment] 2019-09-25 05:43
Hi Diego,

sounds reasonable. Do you want to work on these features?
I'm not a frontend dev :sweat_smile: and I don't see a high need for this since the Simple Monitor should be used only in development.

**Comment by saig0** [comment] 2021-09-22 09:01
The issue is partially solved:
* the pagination has been improved: https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/229
* some of the pages can be sorted: https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/293

I'm closing this issue. Please create new issues for concrete feature requests (instead of having a bulk issue).

**Closed by saig0** 2021-09-22 09:01 UTC
Labels: enhancement, web-app, hacktoberfest
