### ISSUE TITLE
Simple monitor hangs with connection errors when the load on zeebe is high

### ISSUE THREAD

**Issue by lucasledesma** [camunda-community-hub/zeebe-simple-monitor#168] opened 2020-08-04 13:48 UTC
We are using

Zeebe 0.23.4
Hazelcast exporter 0.9.0
Hazelcast 4.0.1 (helm chart 3.4.5)
Simple monitor 0.19.0
Postgres (to persist simple monitor data)

When there are too many workflows running in zeebe, simple monitor can not cope with the amount of data being exported through hazelcast. It gets slower and at the end it gets stuck.

Some logs we could capture.

In the last one we see some connection issues reported and simple monitor can't recover from them

```
java.lang.IllegalArgumentException: Invalid character found in method name [0xc10xbe0xd7A0x100x91]0x17bg]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:418) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-08-04 12:59:21.279  INFO 1 --- [nio-8082-exec-6] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 69900 ms. Closing WebSocketServerSockJsSession[id=4ik0xwcf].
2020-08-04 12:59:21.281  INFO 1 --- [nio-8082-exec-6] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 81988 ms. Closing WebSocketServerSockJsSession[id=f3ce34uo].
2020-08-04 12:59:21.281  INFO 1 --- [nio-8082-exec-6] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 104994 ms. Closing WebSocketServerSockJsSession[id=i10y2mej].
2020-08-04 12:59:21.281  INFO 1 --- [nio-8082-exec-6] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 102799 ms. Closing WebSocketServerSockJsSession[id=tbhguzvf].
2020-08-04 12:59:21.282  INFO 1 --- [nio-8082-exec-6] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 96084 ms. Closing WebSocketServerSockJsSession[id=ys44spjs].
2020-08-04 12:59:21.282  INFO 1 --- [nio-8082-exec-6] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 67713 ms. Closing WebSocketServerSockJsSession[id=5n0ku2bo].
2020-08-04 12:59:21.282  INFO 1 --- [nio-8082-exec-6] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 89065 ms. Closing WebSocketServerSockJsSession[id=vqzlxbvv].
2020-08-04 12:59:21.283  INFO 1 --- [nio-8082-exec-6] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 79823 ms. Closing WebSocketServerSockJsSession[id=jtedgd0y].
2020-08-04 12:59:21.283  INFO 1 --- [nio-8082-exec-6] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 100169 ms. Closing WebSocketServerSockJsSession[id=hduvgu4r].
2020-08-04 13:04:59.333  INFO 1 --- [nio-8082-exec-5] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 335028 ms. Closing WebSocketServerSockJsSession[id=x1zvo52e].
2020-08-04 13:04:59.336  INFO 1 --- [nio-8082-exec-5] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 365036 ms. Closing WebSocketServerSockJsSession[id=wabwrpmc].
2020-08-04 13:04:59.337  INFO 1 --- [nio-8082-exec-5] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 362268 ms. Closing WebSocketServerSockJsSession[id=fk2wdcxf].
2020-08-04 13:04:59.337  INFO 1 --- [nio-8082-exec-5] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 345957 ms. Closing WebSocketServerSockJsSession[id=bbqasyyr].
2020-08-04 13:04:59.338  INFO 1 --- [nio-8082-exec-5] o.s.w.s.m.SubProtocolWebSocketHandler    : No messages received after 355320 ms. Closing WebSocketServerSockJsSession[id=vwpsgejp].


```

```

2020-08-04 13:13:48.167  INFO 1 --- [MessageBroker-2] o.s.w.s.c.WebSocketMessageBrokerStats    : WebSocketSession[2 current WS(1)-HttpStream(1)-HttpPoll(0), 42 total, 28 closed abnormally (28 connect failure, 0 send limit, 2 transport error)], stompSubProtocol[processed CONNECT(11)-CONNECTED(11)-DISCONNECT(10)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 222], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2442], sockJsScheduler[pool size = 2, active threads = 1, queued tasks = 3, completed tasks = 497]
```

**Comment by lucasledesma** [comment] 2020-08-04 14:22
One thing we noticed. When we use simple monitor without an external hazelcast cluster in the middle we don't see this behaviour. However, with that setup only one partition is visible from simple monitor. 
These are the logs we captured from hazelcast, aparently at some point the connection between hazelcast and the client is terminated.

```
Aug 04, 2020 2:03:17 PM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
INFO: [10.230.28.212]:5701 [dev] [4.0.2] Received auth from Connection[id=10, /10.230.28.212:5701->/10.230.28.166:41897, qualifier=null, endpoint=[10.230.28.166]:41897, alive=true, connectionType=JVM], successfully authenticated, clientUuid: f363e606-1c25-4eee-ad53-cdcb73c871ce, client version: 4.0.1
Aug 04, 2020 2:03:18 PM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
INFO: [10.230.28.212]:5701 [dev] [4.0.2] Received auth from Connection[id=11, /10.230.28.212:5701->/10.230.28.37:43003, qualifier=null, endpoint=[10.230.28.37]:43003, alive=true, connectionType=MCJVM], successfully authenticated, clientUuid: c522dff8-fde2-4cda-82f2-dceb9741d786, client version: 4.0.1
Aug 04, 2020 2:03:18 PM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
INFO: [10.230.28.212]:5701 [dev] [4.0.2] Received auth from Connection[id=12, /10.230.28.212:5701->/10.230.28.228:34585, qualifier=null, endpoint=[10.230.28.228]:34585, alive=true, connectionType=JVM], successfully authenticated, clientUuid: fa3b10f5-7093-4f56-af95-3e50cd615baf, client version: 4.0.1
Aug 04, 2020 2:03:18 PM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
INFO: [10.230.28.212]:5701 [dev] [4.0.2] Received auth from Connection[id=13, /10.230.28.212:5701->/10.230.28.24:50661, qualifier=null, endpoint=[10.230.28.24]:50661, alive=true, connectionType=JVM], successfully authenticated, clientUuid: 21be0093-a83d-4ca7-9a46-e35fd9259a4e, client version: 4.0.1
Aug 04, 2020 2:03:19 PM com.hazelcast.client.impl.ClientEngine
INFO: [10.230.28.212]:5701 [dev] [4.0.2] Applying a new client selector :ClientSelector{any}
Aug 04, 2020 2:04:53 PM com.hazelcast.internal.nio.tcp.TcpIpConnection
INFO: [10.230.28.212]:5701 [dev] [4.0.2] Connection[id=2, /10.230.28.212:5701->10-230-28-106.accuv-tools-zeebe-monitor.default.svc.cluster.local/10.230.28.106:38745, qualifier=null, endpoint=[10.230.28.106]:38745, alive=false, connectionType=JVM] closed. Reason: Connection closed by the other side
Aug 04, 2020 2:04:53 PM com.hazelcast.client.impl.ClientEndpointManager
INFO: [10.230.28.212]:5701 [dev] [4.0.2] Destroying ClientEndpoint{connection=Connection[id=2, /10.230.28.212:5701->10-230-28-106.accuv-tools-zeebe-monitor.default.svc.cluster.local/10.230.28.106:38745, qualifier=null, endpoint=[10.230.28.106]:38745, alive=false, connectionType=JVM], clientUuid='a010c593-22a7-4fc4-9625-39b964b3f7e9, authenticated=true, clientVersion=4.0.1, creationTime=1596549748321, latest clientAttributes=lastStatisticsCollectionTime=1596549881476,enterprise=false,clientType=JVM,clientVersion=4.0.1,clusterConnectionTimestamp=1596549748311,clientAddress=10.230.28.106,clientName=hz.client_1,credentials.principal=null,os.committedVirtualMemorySize=0,os.freePhysicalMemorySize=0,os.freeSwapSpaceSize=0,os.maxFileDescriptorCount=0,os.openFileDescriptorCount=0,os.processCpuTime=0,os.systemLoadAverage=0.07,os.totalPhysicalMemorySize=0,os.totalSwapSpaceSize=0,runtime.availableProcessors=2,runtime.freeMemory=54790776,runtime.maxMemory=536870912,runtime.totalMemory=128974848,runtime.uptime=183341,runtime.usedMemory=74184072,executionService.userExecutorQueueSize=0}
Aug 04, 2020 2:05:05 PM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
INFO: [10.230.28.212]:5701 [dev] [4.0.2] Received auth from Connection[id=36, /10.230.28.212:5701->/10.230.28.118:54181, qualifier=null, endpoint=[10.230.28.118]:54181, alive=true, connectionType=JVM], successfully authenticated, clientUuid: 424c498d-9a4b-403c-b1f3-d0cafd62fc35, client version: 4.0.1
Aug 04, 2020 2:15:31 PM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
INFO: [10.230.28.212]:5701 [dev] [4.0.2] Received auth from Connection[id=162, /10.230.28.212:5701->/10.230.29.2:43549, qualifier=null, endpoint=[10.230.29.2]:43549, alive=true, connectionType=JVM], successfully authenticated, clientUuid: 6604bf6b-a597-4130-abf8-7d8dbb3dded7, client version: 4.0.1
```

**Comment by lucasledesma** [comment] 2020-08-04 19:03
We believe it can be related to a race condition. We did the same test using operate and what we see is that under heavy load, the task handlers start to take longer than the timeout set up for those tasks and incidents start to appear due to that reason. 

When this is the case simple monitor hangs, but not operate. And simple monitor can not recover from that point on, even if we delete the monitor pod or even the monitor pod and the hazelcast pods and volumes. 

In one of the tests, we were able to make simple monitor recover by deleting the pod and deleting the entry in the table hazelcast_config. But this is not always the case, in that case we saw incidents coming into the incidents table, but then we could not resolve them because they were pointing to non existent workflows instances. We believed some info might have been lost in the middle.

In operate you can see the incidents pilling up but you can retry them later and they go through.

Hope this information helps. We can try to get more info if that helps you.

Best regards,
Lucas L.-

**Comment by saig0** [comment] 2020-09-07 03:51
@lucasledesma I built a new release `0.19.1`. This includes better failure handling when importing records from Hazelcast.

If the simple monitor is too slow to read all records then it tries to read the next available one instead of stop reading. It might also help to increase the buffer size of Hazelcast's ring-buffer (https://github.com/zeebe-io/zeebe-hazelcast-exporter#configuration).

Please try it out and give feedback :)

**Comment by saig0** [comment] 2021-09-22 08:56
The latest version [2.1.0](https://github.com/camunda-community-hub/zeebe-simple-monitor/releases/tag/2.1.0) improved the handling of Hazelcast connection problems.

Closing this issue under the assumption that the problem is fixed.

**Closed by saig0** 2021-09-22 08:56 UTC
Labels: bug
